version: "3.8"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "123Password!"
      ACCEPT_EULA: "Y"